
import { Product, Order } from './types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Seraphina Diamond Ring',
    description: 'An exquisite diamond ring crafted in 18k white gold, featuring a brilliant-cut center stone surrounded by a halo of smaller diamonds.',
    price: 2500,
    images: ['https://picsum.photos/id/10/800/800', 'https://picsum.photos/id/11/800/800', 'https://picsum.photos/id/12/800/800'],
    metal: 'Platinum',
    category: 'Rings',
    sizes: ['5', '6', '7', '8'],
    stock: 10,
  },
  {
    id: '2',
    name: 'Aurelia Gold Necklace',
    description: 'A timeless piece, this 14k yellow gold necklace features a delicate chain and a polished pendant, perfect for everyday elegance.',
    price: 850,
    images: ['https://picsum.photos/id/20/800/800', 'https://picsum.photos/id/21/800/800'],
    metal: 'Gold',
    category: 'Necklaces',
    stock: 15,
  },
  {
    id: '3',
    name: 'Luna Pearl Earrings',
    description: 'Classic and sophisticated, these freshwater pearl stud earrings are set in sterling silver, offering a touch of grace to any outfit.',
    price: 300,
    images: ['https://picsum.photos/id/30/800/800', 'https://picsum.photos/id/31/800/800'],
    metal: 'Silver',
    category: 'Earrings',
    stock: 25,
  },
  {
    id: '4',
    name: 'Orion Sapphire Bracelet',
    description: 'A stunning bracelet featuring deep blue sapphires and diamonds, set in a flexible platinum link design for maximum comfort and sparkle.',
    price: 4200,
    images: ['https://picsum.photos/id/40/800/800', 'https://picsum.photos/id/41/800/800'],
    metal: 'Platinum',
    category: 'Bracelets',
    stock: 8,
  },
  {
    id: '5',
    name: 'Solstice Gold Hoops',
    description: 'Modern and chic, these lightweight 18k gold hoop earrings are the perfect accessory for both day and night.',
    price: 650,
    images: ['https://picsum.photos/id/50/800/800', 'https://picsum.photos/id/51/800/800'],
    metal: 'Gold',
    category: 'Earrings',
    stock: 20,
  },
  {
    id: '6',
    name: 'Caspian Silver Cuff',
    description: 'A bold statement piece, this handcrafted sterling silver cuff bracelet features an intricate, nature-inspired design.',
    price: 450,
    images: ['https://picsum.photos/id/60/800/800', 'https://picsum.photos/id/61/800/800'],
    metal: 'Silver',
    category: 'Bracelets',
    stock: 12,
  },
  {
    id: '7',
    name: 'Elysian Emerald Ring',
    description: 'A magnificent ring featuring a vibrant, cushion-cut emerald surrounded by a double halo of sparkling diamonds, set in platinum.',
    price: 7800,
    images: ['https://picsum.photos/id/70/800/800', 'https://picsum.photos/id/71/800/800'],
    metal: 'Platinum',
    category: 'Rings',
    sizes: ['6', '7', '8'],
    stock: 5,
  },
  {
    id: '8',
    name: 'Celeste Locket Necklace',
    description: 'A vintage-inspired gold-plated locket to hold your dearest memories close, engraved with a celestial star pattern.',
    price: 320,
    images: ['https://picsum.photos/id/80/800/800', 'https://picsum.photos/id/81/800/800'],
    metal: 'Gold',
    category: 'Necklaces',
    stock: 18,
  },
  {
    id: '9',
    name: 'Nova Diamond Studs',
    description: 'The essential diamond studs. These brilliant-cut diamonds are set in a simple four-prong platinum setting for timeless appeal.',
    price: 1200,
    images: ['https://picsum.photos/id/90/800/800', 'https://picsum.photos/id/91/800/800'],
    metal: 'Platinum',
    category: 'Earrings',
    stock: 15,
  },
  {
    id: '10',
    name: 'Zephyr Chain Bracelet',
    description: 'A delicate and modern chain bracelet in 14k gold, perfect for layering or wearing alone for a minimalist look.',
    price: 280,
    images: ['https://picsum.photos/id/100/800/800', 'https://picsum.photos/id/101/800/800'],
    metal: 'Gold',
    category: 'Bracelets',
    stock: 30,
  },
];


export const ORDERS: Order[] = [
  {
    id: 'ORD-001',
    customerName: 'Jane Doe',
    items: [
      { id: '2', name: 'Aurelia Gold Necklace', price: 850, image: 'https://picsum.photos/id/20/800/800', quantity: 1 },
      { id: '3', name: 'Luna Pearl Earrings', price: 300, image: 'https://picsum.photos/id/30/800/800', quantity: 1 }
    ],
    total: 1150,
    status: 'Shipped',
    date: '2023-10-26',
  },
  {
    id: 'ORD-002',
    customerName: 'John Smith',
    items: [
      { id: '7', name: 'Elysian Emerald Ring', price: 7800, image: 'https://picsum.photos/id/70/800/800', quantity: 1, size: '7' },
    ],
    total: 7800,
    status: 'Delivered',
    date: '2023-10-24',
  },
  {
    id: 'ORD-003',
    customerName: 'Emily White',
    items: [
      { id: '5', name: 'Solstice Gold Hoops', price: 650, image: 'https://picsum.photos/id/50/800/800', quantity: 1 },
      { id: '6', name: 'Caspian Silver Cuff', price: 450, image: 'https://picsum.photos/id/60/800/800', quantity: 1 },
      { id: '10', name: 'Zephyr Chain Bracelet', price: 280, image: 'https://picsum.photos/id/100/800/800', quantity: 2 },
    ],
    total: 1660,
    status: 'Pending',
    date: '2023-10-27',
  },
];
